baseURL = "/"
disableHugoGeneratorInject = true
DefaultContentLanguage = "en"

#Set GDPR compliance settings below
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

#Enable mulitlingual using directories
[languages]
  [languages.en]
    contentDir = 'content/en'
    dataDir = 'data/en'
    languageName = 'English'
    languageCode = 'en'
    weight = 10
  [languages.fr]
    contentDir = 'content/fr'
    dataDir = 'data/fr'
    languageName = 'Français'
    languageCode = 'fr'
    weight = 20

# datocms:start
title = "Clima Capital Partners"

[params]
copyright = "Clima"
# datocms:end
